# Generated by Django 3.1.5 on 2021-01-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile-photos/default-profile-image.jpg', upload_to='profile-photos/'),
        ),
    ]
